version: '3.8'

services:
  php:
    container_name: KDex-php8
    build:
      context: .
      dockerfile: php/.Dockerfile
      args:
        USER_ID:  '${UID:-1000}'
        GROUP_ID: '${GID:-1000}'
        USER:     '${USER:-whoami}'
    restart: always
    ports:
      - "9000:9000"
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - database
      - server
    depends_on:
      - mysql
  nginx:
    container_name: KDex-nginx
    build:
      context: .
      dockerfile: nginx/.Dockerfile
      args:
        USER_ID:  '${UID:-1000}'
        GROUP_ID: '${GID:-1000}'
        USER:     '${USER:-whoami}'
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server
    depends_on:
      - php
      - mysql
  mysql:
    container_name: KDex-db
    build:
      context: .
      dockerfile: mysql/.Dockerfile
      args:
        USER_ID:  '${UID:-1000}'
        GROUP_ID: '${GID:-1000}'
    environment:
      MYSQL_DATABASE:       '${DB_DATABASE:-KDex}'
      MYSQL_USER:           '${DB_USER:-admin}'
      MYSQL_PASSWORD:       '${DB_PASS:-admin}'
      MYSQL_ROOT_PASSWORD:  '${DB_ROOT_PASS:-root}'
    restart: always
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../.env:/var/lib/mysql/.env
      - ../.mysql:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - database

networks:
  server:
    driver: bridge
  database:
    driver: bridge
